### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by PedroCalisto** [petebachant/waveFlapper-OpenFOAM#6]
Hello Pete,
I am trying to running this tutorial, apparently the code works very well and I don't get any error message. But the timesteps directories aren't created and I don't get any data from the code.
I am using openFoam6

**Comment by petebachant** [comment]
Hi Pedro,

I haven't tested this case since OpenFOAM 2.3 or so. You'll probably want to look inside the log files and see if there were any failures.

**Comment by PedroCalisto** [comment]
So, I have this message in the log.blockMesh

--> FOAM FATAL ERROR: 
"/mnt/c/olaFlow/tutorials/waveFlapper-OpenFOAM_BKP/system/blockMeshDict"


    From function int main(int, char**)
    in file blockMesh.C at line 203.

**Comment by PedroCalisto** [comment]
In the log.interDyMFoam 

The dynamic mesh functionality in interDyMFoam has been merged into interFoam
and the interDyMFoam tutorials moved into the interFoam tutorials directory

**Comment by PedroCalisto** [comment]
In the log.setFields 
--> FOAM FATAL ERROR: 
Cannot find file "points" in directory "polyMesh" in times "0" down to constant

    From function virtual Foam::IOobject Foam::fileOperation::findInstance(const Foam::IOobject&, Foam::scalar, const Foam::word&) const
    in file global/fileOperations/fileOperation/fileOperation.C at line 871.

**Comment by PedroCalisto** [comment]
In the log.snappyHexMesh 
--> FOAM FATAL ERROR: 
Cannot find file "points" in directory "polyMesh" in times "0" down to constant

    From function virtual Foam::IOobject Foam::fileOperation::findInstance(const Foam::IOobject&, Foam::scalar, const Foam::word&) const
    in file global/fileOperations/fileOperation/fileOperation.C at line 871.

**Comment by petebachant** [comment]
I believe this is related to #5. Can you submit a PR moving `blockMeshDict` from `constant/polyMesh` into `system`?

**Comment by PedroCalisto** [comment]
I moved the blockMeshDict to the system, but I got the same errors

**Comment by petebachant** [comment]
I just pushed some updates and it seems to be working with OpenFOAM 6. Give it a `git pull` and try again.

**Comment by PedroCalisto** [comment]
Than you very much for your help. Now I can run the simulations, get the timesteps directories and watch the simulation on paraView. It was very helpfull. But I'm still having an issue with `plot.py` file. When I tried to run it in the python3 i got that error message: 
Traceback (most recent call last):
  File "plot.py", line 41, in <module>
    plot_moment()
  File "plot.py", line 20, in plot_moment
    data = foampy.load_forces_moments()
AttributeError: module 'foampy' has no attribute 'load_forces_moments'

**Comment by petebachant** [comment]
I just pushed a fix for that as well.
